#!/usr/bin/env python3
"""Validate the released UAVSwarmV2 YOLO tree and repair a verified bad image.

The current release contains 14,965 ``images/train`` and 6,474 ``images/test``
files.  Its ``test`` directory is the detector validation split.  The archive
contains one zero-byte image; this program replaces only that file with the
byte-identical frame from the accompanying MOT package and records the action.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path


EXPECTED_IMAGES = {"train": 14965, "test": 6474}
NAME = re.compile(r"^(UAVSwarm-\d+)-(\d+)\.jpg$")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument("--mot-root", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    dataset_root = args.dataset_root.expanduser().resolve()
    mot_root = args.mot_root.expanduser().resolve()
    manifest_path = dataset_root / "runtime_manifest.json"
    if manifest_path.exists():
        raise FileExistsError(f"refusing to overwrite existing runtime manifest: {manifest_path}")

    counts: dict[str, dict[str, int]] = {}
    zero_images: list[Path] = []
    for split, expected_count in EXPECTED_IMAGES.items():
        image_dir, label_dir = dataset_root / "images" / split, dataset_root / "labels" / split
        images = sorted(image_dir.glob("*.jpg"))
        labels = sorted(label_dir.glob("*.txt"))
        if len(images) != expected_count or len(labels) != expected_count:
            raise ValueError(f"unexpected {split} counts: images={len(images)}, labels={len(labels)}")
        missing = [image.name for image in images if not (label_dir / f"{image.stem}.txt").is_file()]
        if missing:
            raise ValueError(f"missing labels for {len(missing)} images, e.g. {missing[:3]}")
        counts[split] = {"images": len(images), "labels": len(labels)}
        zero_images.extend(image for image in images if image.stat().st_size == 0)

    repairs = []
    for image in zero_images:
        match = NAME.match(image.name)
        if not match:
            raise ValueError(f"cannot map zero-byte image to MOT source: {image}")
        sequence, frame = match.groups()
        partition = "train" if int(sequence.rsplit("-", 1)[1]) % 2 else "test"
        source = mot_root / partition / sequence / "img1" / f"{int(frame):06d}.jpg"
        if not source.is_file() or source.stat().st_size == 0:
            raise FileNotFoundError(f"verified MOT replacement is unavailable: {source}")
        shutil.copy2(source, image)
        repairs.append({"destination": image.relative_to(dataset_root).as_posix(), "source": str(source), "sha256": sha256(source)})

    yaml_path = dataset_root / "UAVSwarmV2-YOLO.yaml"
    yaml_path.write_text(
        "# Generated by scripts/prepare_uavswarmv2_yolo_runtime.py\n"
        "# The released directory named 'test' is used as detector validation.\n"
        "train: images/train\n"
        "val: images/test\n"
        "names:\n"
        "  0: UAV\n",
        encoding="utf-8",
    )
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_protocol": "released_UAVSwarmV2_YOLO_package",
        "split_directories": {"train": "images/train", "validation": "images/test"},
        "counts": counts,
        "zero_byte_image_repairs": repairs,
        "mot_overlap_warning": "Both detector splits include frames from the MOT train and MOT test partitions; do not use this trained detector for a leakage-free MOT-test tracker comparison.",
        "data_yaml": yaml_path.name,
        "data_yaml_sha256": sha256(yaml_path),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
